using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.Tilemaps;

// Handles moving a colonist along a path generated by the pathfinding system.

public class ColonistMovement : MonoBehaviour
{
    /* Requests a path from PathfindingGrid.
     * Follows the path one grid cell at a time.
     * Only one movement coroutine can run at once.
    */ 

    [SerializeField] private PathfindingGrid pathfindingGrid;
    [SerializeField] private Tilemap groundTilemap;
    [SerializeField] private float moveSpeed = 3f;
    [SerializeField] private JobManager jobManager;

    private Coroutine movementCoroutine;
    private Job currentJob;

    private void Start()
    {
        currentJob = jobManager.GetAvailableJob();

        if (currentJob == null)
            return;

        MoveTo(currentJob.TargetPosition);
    }

    public void MoveTo(Vector3Int targetGridPosition)
    {
        // Convert colonist's position into a grid position before requesting a path.
        Vector3Int startGridPosition = groundTilemap.WorldToCell(transform.position);

        List<Vector3Int> path = pathfindingGrid.FindPath(startGridPosition, targetGridPosition);

        if (path == null || path.Count == 0)
        {
            Debug.LogWarning($"No path found to {targetGridPosition}.");

            return;
        }

        // Cancel the previous movement if a new destination is assigned.
        if (movementCoroutine != null)
            StopCoroutine(movementCoroutine);

        movementCoroutine = StartCoroutine(FollowPath(path));
    }

    private IEnumerator FollowPath(List<Vector3Int> path)
    {
        // Skip the first node since it represents the colonist's current position.
        for (int i = 1; i < path.Count; i++)
        {
            Vector3 targetWorldPosition = groundTilemap.GetCellCenterLocal(path[i]);

            while (Vector3.Distance(transform.position, targetWorldPosition) > 0.01f)
            {
                transform.position = Vector3.MoveTowards(transform.position, targetWorldPosition, moveSpeed * Time.deltaTime);

                yield return null;
            }

            // Snap exactly to the tile center to avoid floating point drift.
            transform.position = targetWorldPosition;
        }

        movementCoroutine = null;

        jobManager.CompleteJob(currentJob);
        currentJob = null;
    }
}
