using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.Tilemaps;
using System;

// Handles moving a colonist along a path generated by the pathfinding system.

public class ColonistMovement : MonoBehaviour
{
    /* Requests a path from PathfindingGrid.
     * Follows the path one grid cell at a time.
     * Only one movement coroutine can run at once.
    */ 

    [SerializeField] private PathfindingGrid pathfindingGrid;
    [SerializeField] private Tilemap groundTilemap;
    [SerializeField] private float moveSpeed = 3f;

    public bool isMoving = false;

    private Coroutine movementCoroutine;

    public void MoveTo(Vector3Int targetGridPosition, Action<bool> onDestinationReached = null)
    {
        // Convert colonist's position into a grid position before requesting a path.
        Vector3Int startGridPosition = groundTilemap.WorldToCell(transform.position);

        List<Vector3Int> path = pathfindingGrid.FindPath(startGridPosition, targetGridPosition);

        if (path == null || path.Count == 0)
        {
            Debug.LogWarning($"No path found to {targetGridPosition}.");
            onDestinationReached?.Invoke(false);
            return;
        }

        // Cancel the previous movement if a new destination is assigned.
        if (movementCoroutine != null)
            StopCoroutine(movementCoroutine);

        movementCoroutine = StartCoroutine(FollowPath(targetGridPosition, path, onDestinationReached));
    }

    private IEnumerator FollowPath(Vector3Int targetGridPosition, List<Vector3Int> path, Action<bool> onDestinationReached)
    {
        isMoving = true;

        // Skip the first node since it represents the colonist's current position.
        for (int i = 1; i < path.Count; i++)
        {
            if (!pathfindingGrid.IsWalkable(path[i]))
            {
                // Attempt to recalculate the path from current position
                Vector3Int currentGridPosition = groundTilemap.WorldToCell(transform.position);
                List<Vector3Int> newPath = pathfindingGrid.FindPath(currentGridPosition, targetGridPosition);

                if (newPath != null && newPath.Count > 1)
                {
                    path = newPath;
                    i = 0; // Will be incremented to 1 by the loop update, so next iteration starts at index 1
                    continue;
                }
                else
                {
                    onDestinationReached?.Invoke(false);
                    yield break;
                }
            }

            Vector3 targetWorldPosition = groundTilemap.GetCellCenterWorld(path[i]);

            while (Vector3.Distance(transform.position, targetWorldPosition) > 0.01f)
            {
                transform.position = Vector3.MoveTowards(transform.position, targetWorldPosition, moveSpeed * Time.deltaTime);

                yield return null;
            }

            // Snap exactly to the tile center to avoid floating point drift.
            transform.position = targetWorldPosition;
        }

        movementCoroutine = null;

        isMoving = false;
        onDestinationReached?.Invoke(true);
    }
}
